packages:
  - 'examples/*'
  - 'e2e/**'
minimumReleaseAgeExclude:
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rslint/*'
  - '@rspack/*'
  - '@rspress/*'
  - '@rstackjs/*'
  - '@rstest/*'
  - '@typescript/*'
  - 'react-server-dom-rspack'
  - 'rsbuild-plugin-*'
  - rstack
  - typescript
